import { NextResponse } from "next/server";

export async function POST() {
  return NextResponse.json(
    {
      message: "Bulk attendance employee listed successfully",
      data: {
        totalCount: 31,
        list: [
          {
            id: "9621cc4f-bb32-40d1-970f-06b701c7ad1b",
            employee_code: "HI86NAL",
            punch_code: "1011",
            avatar: null,
            employee_name: "hinal Rajput",
            department_name: "Trainee Developer",
            sub_department_name: "Trainee Web Developer",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "c9da1495-0727-4618-92d6-a766d15b17d7",
            employee_code: "HI85NAL",
            punch_code: null,
            avatar:
              "https://sixtify.s3.amazonaws.com/1729587236439_images (7).jpg",
            employee_name: "piu Rajput",
            department_name: "Testing Fields",
            sub_department_name: "System Analysis",
            designation_name: "QA Executive",
            reporting_manager_name: "Chirag Sondagar",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "6b0acd5a-362a-4ddf-8d64-fd72c1bb23b6",
            employee_code: "HI84NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Shalini Patil",
            department_name: "Testing Fields",
            sub_department_name: "System Analysis",
            designation_name: "QA Executive",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "30b71c81-8532-46a1-9780-e0dbf3008ddc",
            employee_code: "HI68NAL",
            punch_code: "10548",
            avatar:
              "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
            employee_name: "Jay JK kyada",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "fdcda08b-bfad-4399-9ab6-d6ef4788b058",
            employee_code: "HI67NAL",
            punch_code: "025",
            avatar: null,
            employee_name: "akshay vinubhai gondaliya",
            department_name: "Trainee Developer",
            sub_department_name: "Trainee Web Developer",
            designation_name: "HR Manager",
            reporting_manager_name: "jay Rathod",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "285447cc-2ca7-4539-9f25-8e2108d4c976",
            employee_code: "HI66NAL",
            punch_code: null,
            avatar: "https://example.com/avatar.jpg",
            employee_name: "Alice Jane Williams",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "2832b3db-779e-4f03-a781-c0b966a8dcad",
            employee_code: "HI58NAL",
            punch_code: null,
            avatar:
              "https://sixtify.s3.amazonaws.com/1725885843717_images (2).jpg",
            employee_name: "Raj Ahir",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "tester",
            reporting_manager_name: "Jenish Chanchad",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "593ff82c-0622-4ada-af93-4a58bcb3fa33",
            employee_code: "HI57NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Mahesh Patel",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "1508ddb3-aeea-4e65-b7af-bb795a4a0417",
            employee_code: "HI54NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Mahesh M Patel",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "5d20a9b7-4511-4af9-ab42-f9a799f20587",
            employee_code: "HI53NAL",
            punch_code: "500",
            avatar:
              "https://sixtify.s3.amazonaws.com/1725365928648_images (2).jpg",
            employee_name: "jay Rathod",
            department_name: "Testing Fields",
            sub_department_name: "Testingggggggggg HHHH",
            designation_name: "VP",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "547a30e7-8a6a-4bc9-b07f-5af971efb204",
            employee_code: "HI52NAL",
            punch_code: null,
            avatar: "https://sixtify.s3.amazonaws.com/1726479558971_hero.jpg",
            employee_name: "vaishanvi Rathod",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "QA Executive",
            reporting_manager_name: "vaishanvi Rathod",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "2b54a113-7cfe-4b68-933e-eaf2072d7538",
            employee_code: "HI51NAL",
            punch_code: "123",
            avatar: null,
            employee_name: "Rajput Rajput",
            department_name: "Dept",
            sub_department_name: "Test",
            designation_name: "QA Executive",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "ecb2f688-5d39-42db-b2b9-64ab3ae35798",
            employee_code: "HI50NAL",
            punch_code: "12345",
            avatar: null,
            employee_name: "Jay Jay",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "f6d035d8-8eda-4103-bb03-cc7259906b93",
            employee_code: "HI43NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Manubhai MG Gandhi",
            department_name: "Testing Fields",
            sub_department_name: "Testingggggggggg HHHH",
            designation_name: "VP",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "306e0635-5487-40e7-ad8d-81d28f79ed0a",
            employee_code: "HI24NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Divya DD Divya",
            department_name: "Testing Fields",
            sub_department_name: "Test following functionality in EOD",
            designation_name: "tester1",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "129ecae3-7735-4181-a78a-7c5323975a03",
            employee_code: "HI19NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Divya DD Divya",
            department_name: "Testing Fields",
            sub_department_name: "Test following functionality in EOD",
            designation_name: "tester",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "7bef51e9-ea80-462f-b352-a620f5922299",
            employee_code: "HI18NAL",
            punch_code: "123",
            avatar: null,
            employee_name: "Hinal HG Girase",
            department_name: "Testing Fields",
            sub_department_name: "Test following functionality in EOD",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "9829deec-24ee-4325-912c-b013074bee7f",
            employee_code: "HI17NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Ciaran CC Clemons",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "ece9ff0f-6594-4e33-8aac-7471b0ccde52",
            employee_code: "HI16NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Pritesh PK Kothiya",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "b03197fa-0cd4-44dc-a3e8-abfb41da749e",
            employee_code: "HI14NAL",
            punch_code: "7777",
            avatar:
              "https://sixtify.s3.amazonaws.com/1723805168303_depositphotos_675471232-stock-illustration-lion-king-wild-roars-majestic_1715750732604 - Copy.jpg",
            employee_name: "Bhavik BS Shah",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "1900bf33-702f-4c9c-a80b-3ef28d0242ca",
            employee_code: "HI10NAL",
            punch_code: "3110",
            avatar:
              "https://sixtify.s3.amazonaws.com/1724840218850_bee-on-daisy.jpg",
            employee_name: "Manubhai MG Gandhi",
            department_name: "Testing Fields",
            sub_department_name: "Test following functionality in EOD",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "4b062b76-e6ac-448c-99d1-faa61bc4686d",
            employee_code: "EC1003C",
            punch_code: null,
            avatar: null,
            employee_name: "Dijendra DD Dijendra",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "jay Rathod",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "2137cb32-f380-44fe-ac61-ed891a1313a3",
            employee_code: "HI2NAL",
            punch_code: null,
            avatar: null,
            employee_name: "Manish hamza Manish",
            department_name: "Testing Fields",
            sub_department_name: "Test following functionality in EOD",
            designation_name: "HR Manager",
            reporting_manager_name: "Mahesh Patel",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "00a86dc2-49e0-4aab-a790-74fd6edaebcc",
            employee_code: "MD123D",
            punch_code: null,
            avatar: null,
            employee_name: "Mahesh MP Patel",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "d7ba4f59-d6d5-4125-8ba5-3e5dca2d1e4c",
            employee_code: "DEF456E",
            punch_code: null,
            avatar: null,
            employee_name: "Bob BJ Johnson",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "3baf8a03-e73a-4620-8d2f-e23cbd23f211",
            employee_code: "DRF7894561",
            punch_code: null,
            avatar: null,
            employee_name: "Jons JD Deo",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "28f407c6-eeac-4747-a851-33f8acf0926e",
            employee_code: "XYZ789D",
            punch_code: null,
            avatar: null,
            employee_name: "Alice AS Smith",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "4871673d-eaae-4c81-aa47-3f1515b5cb3e",
            employee_code: "ABC123C",
            punch_code: null,
            avatar: null,
            employee_name: "Frenkg FF Frenkg",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "6c5ed953-54cc-4c31-a582-4bd93dd08436",
            employee_code: "MC999C",
            punch_code: "1001",
            avatar:
              "https://sixtify.s3.amazonaws.com/1725870638552_preview.jpg",
            employee_name: "Chirag Sondagar",
            department_name: "Trainee Developer",
            sub_department_name: "Trainee Web Developer",
            designation_name: "HR Manager",
            reporting_manager_name: "Divya Divya",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "f63571db-bbce-4b7e-a4e1-ef804caae7bb",
            employee_code: "EC1002C",
            punch_code: null,
            avatar: null,
            employee_name: "Demo DD Demo",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "jay Rathod",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
          {
            id: "f8d860f0-c093-4d88-808c-75a23779a105",
            employee_code: "EC1001C",
            punch_code: null,
            avatar: null,
            employee_name: "Jenish R Chanchad",
            department_name: "Research and Development",
            sub_department_name: "System Analysis",
            designation_name: "HR Manager",
            reporting_manager_name: "",
            shift_type_name: "NIGHT (21:00 - 07:00)",
            full_count: "31",
          },
        ],
      },
    },
    { status: 200 }
  );
}
