import { NextResponse } from "next/server";

export async function POST() {
  return NextResponse.json(
    {
      message: "List employees successfully",
      data: {
        totalPages: 1,
        currentPage: 1,
        totalCount: 7,
        employees: [
          {
            id: "df24378f-14c5-44cb-af2c-707e2c4c2696",
            employee_code: "C1001D",
            punch_code: "C1000D",
            employee_name: "Frenkg",
            date_of_birth: "2021-12-31T18:30:00.000Z",
            gender: "Male",
            joining_date: "2023-12-31T18:30:00.000Z",
            on_book_joining_date: "2024-01-31T18:30:00.000Z",
            probation_period: null,
            confirmation_date: "2024-01-31T18:30:00.000Z",
            email: "freankg@gmail.com",
            password: null,
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: "9875543210",
            nick_name: "Frenk",
            avatar: "frenk.jpg",
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: "f878074c-1329-4ac9-8d41-d789766ffb22",
            updated_by: "f878074c-1329-4ac9-8d41-d789766ffb22",
            deleted_by: null,
            created_at: "2024-05-30T03:01:31.714Z",
            updated_at: "2024-05-30T03:01:31.714Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "07818de3-6a6e-451b-9f37-862521968bfd",
            employee_code: "C1000D",
            punch_code: "C1000D",
            employee_name: "Frenk",
            date_of_birth: "2021-12-31T18:30:00.000Z",
            gender: "Male",
            joining_date: "2023-12-31T18:30:00.000Z",
            on_book_joining_date: "2024-01-31T18:30:00.000Z",
            probation_period: null,
            confirmation_date: "2024-01-31T18:30:00.000Z",
            email: "freank@gmail.com",
            password: null,
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: "9876543210",
            nick_name: "Frenk",
            avatar: "frenk.jpg",
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: "f878074c-1329-4ac9-8d41-d789766ffb22",
            updated_by: "f878074c-1329-4ac9-8d41-d789766ffb22",
            deleted_by: null,
            created_at: "2024-05-29T01:42:42.633Z",
            updated_at: "2024-05-29T01:42:42.633Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "fcf3ac5a-b6cd-413c-a714-a3e3157ea33b",
            employee_code: null,
            punch_code: null,
            employee_name: "Chirag S",
            date_of_birth: null,
            gender: "Male",
            joining_date: null,
            on_book_joining_date: null,
            probation_period: null,
            confirmation_date: null,
            email: "chirags.codezee@gmail.com",
            password: "",
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: null,
            nick_name: "Chirag G",
            avatar: null,
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: "2024-05-23T01:56:51.354Z",
            updated_at: "2024-05-23T01:56:51.354Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "5635538d-adf8-4853-81a6-175ee82977e1",
            employee_code: null,
            punch_code: null,
            employee_name: "Manish G",
            date_of_birth: null,
            gender: "Male",
            joining_date: null,
            on_book_joining_date: null,
            probation_period: null,
            confirmation_date: null,
            email: "manishg.codezee@gmail.com",
            password: "",
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: null,
            nick_name: "Manish G",
            avatar: null,
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: "2024-05-23T01:09:39.649Z",
            updated_at: "2024-05-23T01:09:39.649Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "9abf4988-6035-418c-96e0-899fb9ac5876",
            employee_code: null,
            punch_code: null,
            employee_name: "Bhavik",
            date_of_birth: null,
            gender: "Male",
            joining_date: null,
            on_book_joining_date: null,
            probation_period: null,
            confirmation_date: null,
            email: "bhavik@gmail.com",
            password: "",
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: null,
            nick_name: "Bhavik",
            avatar: null,
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: "2024-05-23T01:01:01.650Z",
            updated_at: "2024-05-23T01:01:01.650Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "128605d9-1ac6-4e96-9915-51f5bc3749a6",
            employee_code: null,
            punch_code: null,
            employee_name: "Jenish Chanchad",
            date_of_birth: null,
            gender: "Male",
            joining_date: null,
            on_book_joining_date: null,
            probation_period: null,
            confirmation_date: null,
            email: "jenishc.codezee@gmail.com",
            password: "",
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: null,
            nick_name: "Jenish Chanchad",
            avatar: null,
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: "2024-05-23T00:50:23.996Z",
            updated_at: "2024-05-23T00:50:23.996Z",
            deleted_at: null,
            full_count: "7",
          },
          {
            id: "f878074c-1329-4ac9-8d41-d789766ffb22",
            employee_code: null,
            punch_code: null,
            employee_name: "Kenil Borad",
            date_of_birth: null,
            gender: "Male",
            joining_date: null,
            on_book_joining_date: null,
            probation_period: null,
            confirmation_date: null,
            email: "admin@gmail.com",
            password: "",
            reset_password_otp: null,
            reset_password_expires: null,
            refresh_token: null,
            mobile_no: null,
            nick_name: "ken",
            avatar: null,
            is_active: true,
            rejoined: false,
            is_deleted: false,
            created_by: null,
            updated_by: null,
            deleted_by: null,
            created_at: "2024-05-06T06:50:29.450Z",
            updated_at: "2024-05-06T06:50:29.450Z",
            deleted_at: null,
            full_count: "7",
          },
        ],
      },
    },
    { status: 200 }
  );
}
