import { NextResponse } from "next/server";

export async function POST() {
  return NextResponse.json(
    {
      message: "Business Units fetched successfully.",
      data: {
        totalPages: 1,
        currentPage: 1,
        totalCount: 16,
        businessUnits: [
          {
            id: "8129808b-74de-44c4-91b7-657de95e3533",
            company_id: "2ce7aac1-1bf4-4518-a3b7-53308afa1521",
            business_unit_name: "Code Info",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Jenish Chanchad",
            action_at: "2024-06-26T06:25:30.989Z",
            full_count: "16",
          },
          {
            id: "60617d90-6bcd-4734-9ad1-b6e53f0cdd84",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "Code Info",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Jenish Chanchad",
            action_at: "2024-06-25T12:22:11.542Z",
            full_count: "16",
          },
          {
            id: "25b5d8d0-eea7-44e8-a744-55f124bf0d3e",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "Global Enterprises 123",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Jenish Chanchad",
            action_at: "2024-06-25T11:31:00.513Z",
            full_count: "16",
          },
          {
            id: "8b50d802-e3d9-4703-a300-e4099374143e",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "frdes",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T12:20:23.961Z",
            full_count: "16",
          },
          {
            id: "4295f489-ae93-4203-9b0a-a9618ce328e9",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "edcsx",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:58:54.824Z",
            full_count: "16",
          },
          {
            id: "f96190a9-3ece-48e9-9ca0-1de175de2dec",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "fd",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:58:47.071Z",
            full_count: "16",
          },
          {
            id: "29574b93-3e14-407d-9e8c-f4f20c7cffec",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "fvdcsx",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:48:16.379Z",
            full_count: "16",
          },
          {
            id: "d0451768-8853-4fb5-9a3e-4cdae28b99df",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "fcf",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:48:05.062Z",
            full_count: "16",
          },
          {
            id: "f139b572-35e6-4825-bffc-9ed34bf68d44",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "gevfc sx",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:48:25.326Z",
            full_count: "16",
          },
          {
            id: "cdb1a1c3-be27-4994-86a5-7a95e635ca09",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "dcsxza",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:49.045Z",
            full_count: "16",
          },
          {
            id: "fc45d083-371e-4c62-8e8e-e9fbdad97cf9",
            company_id: "2ce7aac1-1bf4-4518-a3b7-53308afa1521",
            business_unit_name: "fdsa",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "Tech Innovations Inc.1",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:45.199Z",
            full_count: "16",
          },
          {
            id: "27258528-7bf5-4579-9e8e-774eecaa8d23",
            company_id: "2ce7aac1-1bf4-4518-a3b7-53308afa1521",
            business_unit_name: "dsxz",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "Tech Innovations Inc.1",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:38.480Z",
            full_count: "16",
          },
          {
            id: "7d1b044c-ef59-49b7-84e5-81409db525f1",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "fdsx",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:47:56.408Z",
            full_count: "16",
          },
          {
            id: "306e4770-7c9c-4359-a5e9-112927e286f3",
            company_id: "816a2506-91c6-4b23-841d-cd174e42a074",
            business_unit_name: "fcx",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "CMCREATION PVT LTD",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:27.396Z",
            full_count: "16",
          },
          {
            id: "59f38f53-4488-40f0-a6d8-fca4d5fdf51b",
            company_id: "2ce7aac1-1bf4-4518-a3b7-53308afa1521",
            business_unit_name: "f",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "Tech Innovations Inc.1",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:21.708Z",
            full_count: "16",
          },
          {
            id: "3b8e73b6-c45b-4d8f-a093-30c254c62314",
            company_id: "2ce7aac1-1bf4-4518-a3b7-53308afa1521",
            business_unit_name: "rfcd",
            email: "",
            phone_no: "",
            mobile_no: "",
            address: "fr",
            city_id: null,
            state_id: null,
            country_id: null,
            pin_code: "",
            company_name: "Tech Innovations Inc.1",
            city_name: null,
            state_name: null,
            country_name: null,
            action_by: "Bhavik",
            action_at: "2024-06-11T11:46:12.084Z",
            full_count: "16",
          },
        ],
      },
    },
    { status: 200 }
  );
}
